Bugfix/error output refers to sensitive values (#35)
* Add sensitive = true to avoid Terraform failure. 

On running 'terraform apply' with Terraform v1.1.2 it fails with:

Error: Output refers to sensitive values
│
│   on outputs.tf line 5:
│    5: output "user-access-key-secret" {
│
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true

* Add command to extract secret from terraform state file